version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/vite-project
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "81:5173"
    networks:
      - app-network


  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
