name: Deploy to Server

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deployment'
        required: false
        default: 'Manual trigger'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
    
    - name: Deploy to Server
      run: |
        ssh -vv -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Backend Deployment
          
          # Ensure we're in the right directory
          mkdir -p ~/app/backend
          cd ~/yaml-linter

          # Remove existing repository if needed
          rm -rf ${{ github.event.repository.name }} || true

          # Clone repository
          git clone https://github.com/${{ github.repository }} .

          # List contents to verify
          ls -la

          # Update and install tools
          sudo apt-get update
          sudo apt-get install -y git docker.io docker-compose

          # Ensure docker permissions
          sudo usermod -aG docker $USER

          # Stop existing containers (backend)
          docker-compose down || true

          docker-compose up -d --build
          
          echo "Deployment completed"
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
